[package]
name = "rust_fast_cluster"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_fast_cluster"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"
ndarray = "0.15"
ordered-float = "4.2"
